### ISSUE TITLE
crash on lan

### ISSUE THREAD

**Issue by cursinorock** [CrowsOfWar/AvatarMod#21]
When I'm playing on lan with a friend, the game gave this error, unfortunately I do not know how to reproduce, if it happens again I try to write it down
[crash-2017-07-12_18.22.19-server.txt](https://github.com/CrowsOfWar/AvatarMod/files/1143357/crash-2017-07-12_18.22.19-server.txt)

**Comment by CrowsOfWar** [comment]
Thanks for the bug report cursinorock. I found the error - it had to do with killing any mobs without a language file name. It will be fixed in the next patch.

**Comment by cursinorock** [comment]
<3
